version: '3'

services:
  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: ${PGDB_DEFAULT_DB_NAME}
      POSTGRES_USER: ${PGDB_DEFAULT_USER_NAME}
      POSTGRES_PASSWORD: ${PGDB_DEFAULT_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
      CLIENT_ENCODING: UTF8
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
